version: '3.8'

services:
    web:
        container_name: web
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network
        depends_on:
            - db

    db:
        container_name: db
        image: mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root12345678
            MARIADB_DATABASE: db-laravel
            MARIADB_USER: hung
            MARIADB_PASSWORD: hung12345678
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - db-data:/var/lib/mysql
        networks:
            - app-network

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - web

    phpmyadmin:
        container_name: phpmyadmin
        platform: linux/x86_64
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "5000:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - app-network
        depends_on:
            - db

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
